In [1]:
!pip freeze > requirements.txt

In [15]:
import pandas as pd

# read the 2066plan code file
df = pd.read_csv('2066-SchemePlanCode.csv')
df

Unnamed: 0    SchemeCode  SecurityCode  SchemePlanCode  \
0              1  1.405000e+07  1.405000e+07            2066   
1              2  1.405000e+07  1.405000e+07            2066   
2              4  1.405000e+07  1.405000e+07            2066   
3              5  1.405000e+07  1.405000e+07            2066   
4              6  1.405000e+07  1.405000e+07            2066   
...          ...           ...           ...             ...   
8714       16534  1.405188e+08  1.405188e+08            2066   
8715       16536  1.405188e+08  1.405188e+08            2066   
8716       16537  1.405188e+08  1.405188e+08            2066   
8717       16538  1.405188e+08  1.405188e+08            2066   
8718       16539  1.405188e+08  1.405188e+08            2066   

     SchemePlanDescription MappingCode  \
0                   Growth      100656   
1                   Growth      100651   
2                   Growth       1#220   
3                   Growth       1#359   
4                   Growth       2#226   
...                    ...         ...   
8714                Growth    152582.0   
8715                Growth    152590.0   
8716                Growth    152588.0   
8717                Growth    152587.0   
8718                Growth    152586.0   

                                            MappingName  IssuePrice  \
0           UTI - Master Plus Unit Scheme-Growth Option         0.0   
1                      UTI - Master Share-Growth Option         0.0   
2                                              CANBONUS         0.0   
3                                            CANTRIPLE+         0.0   
4                                             CANPEP 95         0.0   
...                                                 ...         ...   
8714        TRUSTMF Flexi Cap Fund-Regular Plan- Growth         0.0   
8715  Tata Nifty500 Multicap India Manufacturing 50 ...         0.0   
8716  Tata Nifty500 Multicap India Manufacturing 50 ...         0.0   
8717  Samco Special Opportunities Fund - Regular Pla...         0.0   
8718  Samco Special Opportunities Fund - Direct Plan...         0.0   

                                            Description IssueDate  ...  \
0                        UTI Master Plus 91 Unit Scheme       NaN  ...   
1                                       UTI Mastershare       NaN  ...   
2                                              Canbonus       NaN  ...   
3                                          Cantriple(G)       NaN  ...   
4                                         Canpep '95(G)       NaN  ...   
...                                                 ...       ...  ...   
8714                             TRUSTMF Flexi Cap Fund       NaN  ...   
8715  Tata Nifty500 Multicap India Manufacturing 50 ...       NaN  ...   
8716  Tata Nifty500 Multicap India Manufacturing 50 ...       NaN  ...   
8717                   Samco Special Opportunities Fund       NaN  ...   
8718     Samco Special Opportunities Fund - Direct Plan       NaN  ...   

     ISINCode  BenchMarkIndex        BenchMarkIndexName         ModifiedDate  \
0         NaN    1.702393e+07            S&P BSE Sensex  2015-12-15 19:12:12   
1         NaN    1.702393e+07  S&P BSE 100 Total Return  2020-01-08 19:49:52   
2         NaN    1.702393e+07            S&P BSE Sensex  2015-12-15 19:12:12   
3         NaN    1.702393e+07            S&P BSE Sensex  2015-12-15 19:12:12   
4         NaN    1.702393e+07            S&P BSE Sensex  2015-12-15 19:12:12   
...       ...             ...                       ...                  ...   
8714      NaN    1.702393e+07    NIfty 500 Total Return  2024-04-01 17:11:17   
8715      NaN             NaN                       NaN  2024-04-02 10:05:57   
8716      NaN             NaN                       NaN  2024-04-02 10:06:43   
8717      NaN    1.702393e+07    NIfty 500 Total Return  2024-04-02 10:27:44   
8718      NaN    1.702393e+07    NIfty 500 Total Return  2024-04-02 10:27:58   

      DeleteFlag      scheme_

In [8]:
df.columns

Index(['Unnamed: 0', 'SchemeCode', 'SecurityCode', 'SchemePlanCode',
       'SchemePlanDescription', 'MappingCode', 'MappingName', 'IssuePrice',
       'Description', 'IssueDate', 'ExpiryDate', 'FaceValue', 'MarketLot',
       'ISINCode', 'BenchMarkIndex', 'BenchMarkIndexName', 'ModifiedDate',
       'DeleteFlag', 'scheme_name', 'scheme_category', 'date',
       'btt_scheme_code', 'btt_scheme_category'],
      dtype='object')

In [11]:
df['SchemePlanDescription'].unique()

array(['Growth', '41-TRIAL-Growth 167'], dtype=object)

In [58]:
df['BenchMarkIndex'].unique()

array([17023928.00026005, 14010005.00026005, 17023929.00026005,
       14010046.00026005, 17024232.00026005,               nan,
       17024233.00026005, 14094912.00026005, 17024234.00026005,
       17024235.00026005, 14094912.00026004, 17023929.00026006])

In [27]:
# check if the description is same as the scheme name
check = df[df['scheme_name'].notnull()]['Description'] == df[df['scheme_name'].notnull()]['scheme_name']
# count of false in check
check.value_counts()

True     404
False     65
dtype: int64

In [52]:
categories = df['scheme_category'].unique()

In [49]:
equity_largecap = df[df['scheme_category']=='Equity-LargeCap']
equity_largecap['BenchMarkIndex'].unique()

array([17023928.00026005, 17023929.00026005, 14010005.00026005])

In [51]:
check = df.loc[df['BenchMarkIndex'].isin([17023928.00026005, 17023929.00026005, 14010005.00026005]), 'scheme_category'] =='Equity-LargeCap'
check.value_counts()

False    8070
True       79
Name: scheme_category, dtype: int64

In [57]:
for category in categories:
    # print(category)
    cat_filter = df[df['scheme_category'] == category]
    cap_unique = cat_filter['BenchMarkIndex'].unique()

    check = df.loc[df['BenchMarkIndex'].isin(cap_unique), 'scheme_category'] == category
    # print(check.value_counts())

    if check.value_counts().get(True) == len(cat_filter):
        # print(check.value_counts().get(True))
        print(cap_unique, " are the unique BenchMarkIndex for ", category)
    else:
        print("There are multiple BenchMarkIndex for ", category) 
        # print(check.value_counts().get(False))


There are multiple BenchMarkIndex for  nan
[17023928.00026005 17023929.00026005 14010005.00026005]  are the unique BenchMarkIndex for  Equity-LargeCap
[14010005.00026005 17023929.00026005 17023928.00026005]  are the unique BenchMarkIndex for  Hybrid-EquityOriented
[17023929.00026005 17023928.00026005]  are the unique BenchMarkIndex for  Equity-TaxPlanning
[17023929.00026005 14010005.00026005]  are the unique BenchMarkIndex for  Debt-UltraShortTerm
[14010005.00026005 17023929.00026005]  are the unique BenchMarkIndex for  Hybrid-Debt-orientedConservative
[17023928.00026005]  are the unique BenchMarkIndex for  Equity-Technology
[17023929.00026005 17023928.00026005]  are the unique BenchMarkIndex for  Equity-Others
[14010005.00026005 14010046.00026005 17023929.00026005]  are the unique BenchMarkIndex for  Debt-GiltMedium&LongTerm
[14010005.00026005 17023929.00026005 17023928.00026005]  are the unique BenchMarkIndex for  Hybrid-Debt-orientedAggressive
[17023929.00026005 14010005.00026005]  

In [22]:
import psycopg2
import pandas as pd
conn = psycopg2.connect(
    host="192.168.29.162",
    port=5432,
    database="BravisaDB",
    user="postgres",
    password="edsols")

cur = conn.cursor()

sql = """ select * from public."IndustryDivisor"
            where "IndexName" = 'INDUSTRY-Consumer Staples Distribution & Retail'
            order by "Date" """

sec_div  = pd.read_sql_query(sql, conn)

# rename sec_div['IndexValue'] to ff_close_sum
sec_div.rename(columns={'IndexValue':'ff_close_sum(Cr)', "Divisor":"Divisor(Cr)"}, inplace=True)
# sec_div.rename()
len(sec_div)

C:\Users\Admin\AppData\Local\Temp\ipykernel_5228\724550513.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sec_div  = pd.read_sql_query(sql, conn)


1061

In [23]:
sec_div['ff_close_sum(Cr)'] = sec_div['ff_close_sum(Cr)'].apply(lambda x: str(round(float(x/10000000), 2)) if x > 10000000 else x)
sec_div['Divisor(Cr)'] = sec_div['Divisor(Cr)'].apply(lambda x: str(round(float(x/1000000), 2)) if x > 1000000 else x)

In [24]:
sec_div.to_csv('INDUSTRY-Consumer Staples Distribution & Retail.csv', index=False)

In [50]:
import psycopg2
import pandas as pd
conn = psycopg2.connect(
    host="192.168.29.162",
    port=5432,
    database="BravisaDB",
    user="postgres",
    password="edsols")

cur = conn.cursor()

sql = """ select * from public."SubIndustryIndexList"
            where "SubIndustryIndexName" = 'SUBINDUSTRY-Trading'
            order by "GenDate" """

indexList  = pd.read_sql_query(sql, conn)

indexList.to_csv('IRS/IndexList - SUBINDUSTRY-Trading.csv', index=False)



C:\Users\Admin\AppData\Local\Temp\ipykernel_5228\1776443147.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  indexList  = pd.read_sql_query(sql, conn)


In [52]:
import psycopg2
import pandas as pd
conn = psycopg2.connect(
    host="192.168.29.162",
    port=5432,
    database="BravisaDB",
    user="postgres",
    password="edsols")

cur = conn.cursor()

sql = """ select * from public."IndustryList"
            where "SubIndustryIndexName" = 'SUBINDUSTRY-Trading'
            order by "GenDate" """

IndustryList  = pd.read_sql_query(sql, conn)

col = ['FF_Open', 'FF_High', 'FF_Low', 'FF_Close', 'PAT', 'Equity', 'OS_Close', 'prev_pat',
       'prev_equity',  'OS']

# for c in col:
#         IndustryList[c] = IndustryList[c].apply(lambda x: (round(float(x/10000000), 2)) if x > 10000000 else x)

IndustryList.to_csv('IRS/IndustryList - SUBINDUSTRY-Trading.csv', index=False)

C:\Users\Admin\AppData\Local\Temp\ipykernel_5228\2763819712.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  IndustryList  = pd.read_sql_query(sql, conn)


# Resistance and support

In [ ]:
import pandas as pd
import psycopg2
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")

# connection to the database
industry_list = []  # Initialize the 'industry_list' variable

conn = psycopg2.connect(
    host="192.168.1.162",
    port=5432,
    database="BravisaDB",
    user="postgres",
    password="edsols")

cur = conn.cursor()

In [5]:
# Let's generate a new Excel file with slight inconsistencies as per the user's request.
import pandas as pd
import numpy as np

# Creating the Customers Table
customers = pd.DataFrame({
    "CustomerID": np.arange(1, 11),
    "CustomerName": ["John Doe", "Jane Smith", "Mark Taylor", "Emily Johnson", "Chris Brown",
                     "Ava Davis", "Liam Wilson", "Mia White", "Noah Harris", "Sophia Clark"],
    "Email": ["john.doe@example.com", "jane.smith@example.com", "mark.taylor@example.com", "emily.johnson@example.com", 
              "chris.brown@example.com", "ava.davis@example.com", np.nan, "mia.white@example.com", 
              "noah.harris@example.com", "sophia.clark@example.com"],  # One missing email
    "PhoneNumber": ["123-456-7890", "234-567-8901", "345-678-9012", "456-789-0123", "567-890-1234",
                    "678-901-2345", "789-012-3456", "890-123-4567", "901-234-5678", np.nan],  # One missing phone number
    "Region": ["North", "South", "East", "West", "North", "South", "East", "West", "North", "south"]  # One inconsistency in Region capitalization
})

# Creating the Sales Table
sales = pd.DataFrame({
    "TransactionID": np.arange(1, 21),
    "CustomerID": np.random.choice(customers["CustomerID"], 20),
    "ProductID": np.random.randint(1, 6, 20),
    "Quantity": np.random.randint(1, 11, 20),
    "SalesAmount": [100.5, 200, 150, "???", 300, 400, 350, 250, 500, 600, 450, 550, 650, 700, 750, 800, 850, 900, 950, 1000],  # One incorrect entry
    "TransactionDate": pd.to_datetime(np.random.choice(pd.date_range("2023-01-01", "2024-01-01"), 20))
})

# Fixing the incorrect date
sales["TransactionDate"] = sales["TransactionDate"].astype(str).replace("2024-02-30", "2024-02-28")
sales["TransactionDate"] = pd.to_datetime(sales["TransactionDate"])

# Creating the Products Table
products = pd.DataFrame({
    "ProductID": np.arange(1, 6),
    "ProductName": ["Laptop", "Smartphone", "Tablet", "Monitor", "Wearable"],
    "Category": ["Electronics", "Electronics", "Electronics", "Electronics", "Wearables"],
    "Price": [1000, 500, 300, 200, 150]
})

# Creating the Regions Table
regions = pd.DataFrame({
    "Region": ["North", "South", "East", "West"],
    "Manager": ["Alice", "Bob", "Charlie", "Diana"],
    "RegionCode": ["NR", "SR", "ER", "WR"]
})

# Create a dictionary to store the tables
dataframes = {"Customers": customers, "Sales": sales, "Products": products, "Regions": regions}

# Define the file path
file_path = "customer_profitability_analysis.xlsx"

# Create an Excel writer object
writer = pd.ExcelWriter(file_path)

# Iterate over the dataframes dictionary
for sheet_name, df in dataframes.items():
    # Write each dataframe to a separate sheet in the Excel file
    df.to_excel(writer, sheet_name=sheet_name, index=False)

# Save the Excel file
writer.save()



C:\Users\Admin\AppData\Local\Temp\ipykernel_5872\1905138399.py:62: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
